# Generated by Django 2.1.7 on 2019-05-07 03:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Reseña')),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ejemplar_libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador del ejemplar', primary_key=True, serialize=False)),
                ('orden_compra', models.CharField(blank=True, help_text='Ingrese nro. orden de compra', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('sinopsis', models.TextField(blank=True, help_text='Ingrese la sinopsis', max_length=1000, null=True)),
                ('cantidad_ejemplares', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad de ejemplares')),
                ('autor', models.ForeignKey(help_text='Seleccione un autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Autor')),
                ('categoria', models.ManyToManyField(help_text='Seleccione una categoría', to='aplicacion.Categoria')),
                ('editorial', models.ForeignKey(help_text='Seleccione una editorial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Editorial')),
                ('idioma', models.ForeignKey(help_text='Seleccione un idioma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('encargado', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar_libro',
            name='estado',
            field=models.ForeignKey(help_text='Seleccione estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Estado'),
        ),
        migrations.AddField(
            model_name='ejemplar_libro',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Libro'),
        ),
        migrations.AddField(
            model_name='ejemplar_libro',
            name='sucursal',
            field=models.ForeignKey(help_text='Seleccione una sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Sucursal'),
        ),
    ]
