package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetVentaId generated by hbm2java
 */
public class DetVentaId  implements java.io.Serializable {


     private String idVenta;
     private BigDecimal idLibro;

    public DetVentaId() {
    }

    public DetVentaId(String idVenta, BigDecimal idLibro) {
       this.idVenta = idVenta;
       this.idLibro = idLibro;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public BigDecimal getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(BigDecimal idLibro) {
        this.idLibro = idLibro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetVentaId) ) return false;
		 DetVentaId castOther = ( DetVentaId ) other; 
         
		 return ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) )
 && ( (this.getIdLibro()==castOther.getIdLibro()) || ( this.getIdLibro()!=null && castOther.getIdLibro()!=null && this.getIdLibro().equals(castOther.getIdLibro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         result = 37 * result + ( getIdLibro() == null ? 0 : this.getIdLibro().hashCode() );
         return result;
   }   


}


