package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private BigDecimal idEstado;
     private String nombreEstado;

    public Estado() {
    }

    public Estado(BigDecimal idEstado, String nombreEstado) {
       this.idEstado = idEstado;
       this.nombreEstado = nombreEstado;
    }
   
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }




}


