package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
@JsonIgnoreProperties(value = { "detVentas" })
public class Libro  implements java.io.Serializable {


     private BigDecimal idLibro;
     private Autor autor;
     private String tituloLibro;
     private String isbnLibro;
     private String sinopsisLibro;
     private short cantidadejemplaresLibro;
     private int precioLibro;
     private Set<DetVenta> detVentas = new HashSet<DetVenta>(0);

    public Libro() {
    }

	
    public Libro(BigDecimal idLibro, Autor autor, String tituloLibro, String isbnLibro, short cantidadejemplaresLibro, int precioLibro) {
        this.idLibro = idLibro;
        this.autor = autor;
        this.tituloLibro = tituloLibro;
        this.isbnLibro = isbnLibro;
        this.cantidadejemplaresLibro = cantidadejemplaresLibro;
        this.precioLibro = precioLibro;
    }
    public Libro(BigDecimal idLibro, Autor autor, String tituloLibro, String isbnLibro, String sinopsisLibro, short cantidadejemplaresLibro, int precioLibro, Set<DetVenta> detVentas) {
       this.idLibro = idLibro;
       this.autor = autor;
       this.tituloLibro = tituloLibro;
       this.isbnLibro = isbnLibro;
       this.sinopsisLibro = sinopsisLibro;
       this.cantidadejemplaresLibro = cantidadejemplaresLibro;
       this.precioLibro = precioLibro;
       this.detVentas = detVentas;
    }
   
    public BigDecimal getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(BigDecimal idLibro) {
        this.idLibro = idLibro;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public String getTituloLibro() {
        return this.tituloLibro;
    }
    
    public void setTituloLibro(String tituloLibro) {
        this.tituloLibro = tituloLibro;
    }
    public String getIsbnLibro() {
        return this.isbnLibro;
    }
    
    public void setIsbnLibro(String isbnLibro) {
        this.isbnLibro = isbnLibro;
    }
    public String getSinopsisLibro() {
        return this.sinopsisLibro;
    }
    
    public void setSinopsisLibro(String sinopsisLibro) {
        this.sinopsisLibro = sinopsisLibro;
    }
    public short getCantidadejemplaresLibro() {
        return this.cantidadejemplaresLibro;
    }
    
    public void setCantidadejemplaresLibro(short cantidadejemplaresLibro) {
        this.cantidadejemplaresLibro = cantidadejemplaresLibro;
    }
    public int getPrecioLibro() {
        return this.precioLibro;
    }
    
    public void setPrecioLibro(int precioLibro) {
        this.precioLibro = precioLibro;
    }
    public Set<DetVenta> getDetVentas() {
        return this.detVentas;
    }
    
    public void setDetVentas(Set<DetVenta> detVentas) {
        this.detVentas = detVentas;
    }




}


