package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoUs generated by hbm2java
 */
@JsonIgnoreProperties(value = { "usuarios" })
public class TipoUs  implements java.io.Serializable {


     private BigDecimal idTipo;
     private String nombreTipo;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUs() {
    }

	
    public TipoUs(BigDecimal idTipo, String nombreTipo) {
        this.idTipo = idTipo;
        this.nombreTipo = nombreTipo;
    }
    public TipoUs(BigDecimal idTipo, String nombreTipo, Set<Usuario> usuarios) {
       this.idTipo = idTipo;
       this.nombreTipo = nombreTipo;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


