package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDoc generated by hbm2java
 */
@JsonIgnoreProperties(value = { "ventas" })
public class TipoDoc  implements java.io.Serializable {


     private BigDecimal idTipoDoc;
     private String nombreTipoDocumento;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public TipoDoc() {
    }

	
    public TipoDoc(BigDecimal idTipoDoc, String nombreTipoDocumento) {
        this.idTipoDoc = idTipoDoc;
        this.nombreTipoDocumento = nombreTipoDocumento;
    }
    public TipoDoc(BigDecimal idTipoDoc, String nombreTipoDocumento, Set<Venta> ventas) {
       this.idTipoDoc = idTipoDoc;
       this.nombreTipoDocumento = nombreTipoDocumento;
       this.ventas = ventas;
    }
   
    public BigDecimal getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(BigDecimal idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public String getNombreTipoDocumento() {
        return this.nombreTipoDocumento;
    }
    
    public void setNombreTipoDocumento(String nombreTipoDocumento) {
        this.nombreTipoDocumento = nombreTipoDocumento;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


