package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
@JsonIgnoreProperties(value = {"ventas"})
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private TipoUs tipoUs;
     private Sucursal sucursal;
     private String nombreUsuario;
     private String rutUsuario;
     private String contrasenaUsuario;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Usuario() {
    }

	
    public Usuario(BigDecimal idUsuario, TipoUs tipoUs, Sucursal sucursal, String nombreUsuario, String rutUsuario, String contrasenaUsuario) {
        this.idUsuario = idUsuario;
        this.tipoUs = tipoUs;
        this.sucursal = sucursal;
        this.nombreUsuario = nombreUsuario;
        this.rutUsuario = rutUsuario;
        this.contrasenaUsuario = contrasenaUsuario;
    }
    public Usuario(BigDecimal idUsuario, TipoUs tipoUs, Sucursal sucursal, String nombreUsuario, String rutUsuario, String contrasenaUsuario, Set<Venta> ventas) {
       this.idUsuario = idUsuario;
       this.tipoUs = tipoUs;
       this.sucursal = sucursal;
       this.nombreUsuario = nombreUsuario;
       this.rutUsuario = rutUsuario;
       this.contrasenaUsuario = contrasenaUsuario;
       this.ventas = ventas;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUs getTipoUs() {
        return this.tipoUs;
    }
    
    public void setTipoUs(TipoUs tipoUs) {
        this.tipoUs = tipoUs;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getRutUsuario() {
        return this.rutUsuario;
    }
    
    public void setRutUsuario(String rutUsuario) {
        this.rutUsuario = rutUsuario;
    }
    public String getContrasenaUsuario() {
        return this.contrasenaUsuario;
    }
    
    public void setContrasenaUsuario(String contrasenaUsuario) {
        this.contrasenaUsuario = contrasenaUsuario;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


