package pojos;
// Generated 13-06-2019 3:33:06 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
@JsonIgnoreProperties(value = {"detVentas","usuario","tipoDoc"})
public class Venta  implements java.io.Serializable {


     private String idVenta;
     private Usuario usuario;
     private TipoDoc tipoDoc;
     private Date fechaVenta;
     private String rutcliente;
     private String nombrecliente;
     private String razonsocialFactura;
     private String rutFactura;
     private String direccionFactura;
     private String giroFactura;
     private String contactoFactura;
     private String ciudadFactura;
     private Set<DetVenta> detVentas = new HashSet<DetVenta>(0);

    public Venta() {
    }

	
    public Venta(String idVenta, Usuario usuario, TipoDoc tipoDoc, Date fechaVenta, String rutcliente, String nombrecliente) {
        this.idVenta = idVenta;
        this.usuario = usuario;
        this.tipoDoc = tipoDoc;
        this.fechaVenta = fechaVenta;
        this.rutcliente = rutcliente;
        this.nombrecliente = nombrecliente;
    }
    public Venta(String idVenta, Usuario usuario, TipoDoc tipoDoc, Date fechaVenta, String rutcliente, String nombrecliente, String razonsocialFactura, String rutFactura, String direccionFactura, String giroFactura, String contactoFactura, String ciudadFactura, Set<DetVenta> detVentas) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.tipoDoc = tipoDoc;
       this.fechaVenta = fechaVenta;
       this.rutcliente = rutcliente;
       this.nombrecliente = nombrecliente;
       this.razonsocialFactura = razonsocialFactura;
       this.rutFactura = rutFactura;
       this.direccionFactura = direccionFactura;
       this.giroFactura = giroFactura;
       this.contactoFactura = contactoFactura;
       this.ciudadFactura = ciudadFactura;
       this.detVentas = detVentas;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public TipoDoc getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(TipoDoc tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getRutcliente() {
        return this.rutcliente;
    }
    
    public void setRutcliente(String rutcliente) {
        this.rutcliente = rutcliente;
    }
    public String getNombrecliente() {
        return this.nombrecliente;
    }
    
    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }
    public String getRazonsocialFactura() {
        return this.razonsocialFactura;
    }
    
    public void setRazonsocialFactura(String razonsocialFactura) {
        this.razonsocialFactura = razonsocialFactura;
    }
    public String getRutFactura() {
        return this.rutFactura;
    }
    
    public void setRutFactura(String rutFactura) {
        this.rutFactura = rutFactura;
    }
    public String getDireccionFactura() {
        return this.direccionFactura;
    }
    
    public void setDireccionFactura(String direccionFactura) {
        this.direccionFactura = direccionFactura;
    }
    public String getGiroFactura() {
        return this.giroFactura;
    }
    
    public void setGiroFactura(String giroFactura) {
        this.giroFactura = giroFactura;
    }
    public String getContactoFactura() {
        return this.contactoFactura;
    }
    
    public void setContactoFactura(String contactoFactura) {
        this.contactoFactura = contactoFactura;
    }
    public String getCiudadFactura() {
        return this.ciudadFactura;
    }
    
    public void setCiudadFactura(String ciudadFactura) {
        this.ciudadFactura = ciudadFactura;
    }
    public Set<DetVenta> getDetVentas() {
        return this.detVentas;
    }
    
    public void setDetVentas(Set<DetVenta> detVentas) {
        this.detVentas = detVentas;
    }




}


